### ISSUE TITLE
Talk with OpenSocial team + Product Owner

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/drupal_social#6]

**Comment by ribel** [comment]
Talked about Drupal Camp and Code Sprint to Taco Potze (Product Owner of Open Social).
He is interested in visiting event, possibly with Lead Dev and Scrum Master of OS. Also interested in sponsoring of event.

**Comment by ribel** [comment]
As result of this task, three speakers from Open Social team:
http://camp17.drupal.ua/en/speakers/moving-drupalshop-services-products
http://camp17.drupal.ua/en/speakers/learning-about-ideal-scrum-team-size
http://camp17.drupal.ua/en/speakers/open-social-case-studies
