### ISSUE TITLE
Find people for the spring

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/drupal_social#8]
Developers needed
See initial post https://www.facebook.com/groups/104220905217/permalink/10154825325510218/

**Comment by ribel** [comment]
Team A members:

**Taras Kruts**
- https://www.drupal.org/u/ribel
- https://github.com/ribel

**Oleksandr Maksymiuk**
- https://www.drupal.org/u/alexksis
- https://github.com/ksis

**Taras Kyryliuk**
- https://www.drupal.org/u/tarasich
- https://github.com/tkyryliuk

**Andrew Ivasiv**
- https://www.drupal.org/u/andrew147
- https://github.com/andriy-ivasiv

**Andriy Khomych**
- https://www.drupal.org/u/andriy-khomych
- https://github.com/a-kom

**Mykhailo Gurei**
- https://www.drupal.org/u/ozin
- https://github.com/ozin7

**Oleh Vehera**
- https://www.drupal.org/u/voleger
- https://github.com/iVegas

**Mykhailo Semkulych**
- https://www.drupal.org/u/t0r
- https://github.com/semkulich

**Comment by ribel** [comment]
@podarok see updated info ^

**Comment by ribel** [comment]
Team B members:
 
**Anton Martyniuk**
- https://www.drupal.org/user/3079615/
- https://github.com/AntonMartyniuk

**Volodymyr Martsynenko**
- https://www.drupal.org/u/makishima
- https://github.com/VolodymyrMartsynenko

**Vlad Nosykov**
- https://www.drupal.org/u/vlad-nosykov
- https://github.com/vladnosykov

**Volodymyr Sydor**
- https://www.drupal.org/u/sv
